//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace simpress_challenge.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tblProduto
    {
        public int Id { get; set; }

        [Required]
        [StringLength(250, MinimumLength = 5)]
        public string Nome { get; set; }

        [Required]
        [StringLength(250, MinimumLength = 5)]
        public string Descricao { get; set; }

        [Required]
        public bool Ativo { get; set; }

        [Required]
        public bool Perecivel { get; set; }

        [Required]
        public int CategoriaID { get; set; }
    
        public virtual tblCategoriaProduto tblCategoriaProduto { get; set; }
    }
}
